server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tnews?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true